version: "3.9"

services:
  database:
    image: postgres
    container_name: database_popmovies
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=popmovies
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: popmovies
    restart: always
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local
